### PR TITLE
Group Sonos Alarm with Sonos devices

### PR DESCRIPTION
**Pull request by AaronDavidSchneider**
- Fix device name
- migrate to new device if room is changed
- clean up old devices

### CODE REVIEW

**Comment by AaronDavidSchneider** [comment]
This PR picks up on the discussion in #25 and #24.
I would love to hear your feedback @rasmusbe and @christianschneider89

**Comment by christianschneider89** [comment]
I installed the version and I got following before changing:
image

And this after I changed the room of an an alarm:
image
(I also changed the time from 8 to 7)

Is this behavior correct?

**Comment by rasmusbe** [comment]
I tried it and it works flawless with room changes.

I also tried removing an alarm and when I did the entity first became "Unavailable"
image
and after a restart it became "Restored"
image

I'm not sure if it is possible to remove the entity completely (since it's never going to come back with the same ID) or if this is the best we can do. Anyways this is a great improvement 👍

**Comment by AaronDavidSchneider** [comment]
Thank you for your tests!
I will think about the possibility to remove the entity once not available.
You are totally right. The alarm id will never come back anyway :D

**Comment by AaronDavidSchneider** [comment]
Here we go @christianschneider89 and @rasmusbe.
The devices should now be removed, when the alarm is deleted.
Can you confirm?

**Comment by rasmusbe** [comment]
Works great while HA is running but I also tried to remove the alarm while HA was stopped. Then the alarm entity became "Restored" instead of being removed. Not a big deal thou
image

**Comment by AaronDavidSchneider** [comment]
> Works great while HA is running but I also tried to remove the alarm while HA was stopped. Then the alarm entity became "Restored" instead of being removed. Not a big deal thou
> image

Thanks for testing. I don't know how to fix that. But I suppose that will rarely ever happen in reality :D

**Comment by rasmusbe** [comment]
I totally agree :D

**Comment by AaronDavidSchneider** [comment]
I released it. Thanks for your help!

**Pull request merged**
