### PR TITLE
add scheduled_today attribute

### PR DESCRIPTION
**Pull request by AaronDavidSchneider**
This adds the `scheduled_today` attribute and fixes issue #14 .

### CODE REVIEW

**Comment by AaronDavidSchneider** [comment]
Could you please test @dennisbrouwer91?

Let me know if you need help setting it up :D

**Comment by dennisbrouwer91** [comment]
Will test this today and report back :D

**Comment by dennisbrouwer91** [comment]
@AaronDavidSchneider After applying the patch the switches go to Unavailable on my side!

**Comment by AaronDavidSchneider** [comment]
Should be fixed now. Unfortunately I had to manually implement the function to determine it.

**Comment by AaronDavidSchneider** [comment]
It doesn't check if the alarm should already been scheduled.
So example:
Its true even though its past the alarm time.

**Comment by dennisbrouwer91** [comment]
Thanks again for the update. Installed the patched file and seeing this in the log after adding the integration : 
Screenshot 2021-03-04 at 08 33 55

But i'm not getting the new sonos_alarm devices as entity.
Every minute i also see this in the logs : 
Screenshot 2021-03-04 at 08 35 45

Any idea?

**Comment by AaronDavidSchneider** [comment]
Did you try to restart ha and readd the integration?
The upper log shows that there is no switch initialized (or you have still outdated files).

Is there actually an alarm that ha can control? If not we won't get a switch.

We can schedule a quick bug fixing zoom session if you like.

**Comment by dennisbrouwer91** [comment]
Did a full HA restart indeed, removed integration, restart again, re-added integration. There are 3 alarms set in the Sonos App.

Zoom session sounds good. Thanks so much for all the work!

Edit: Removed your mail for security reasons.

**Pull request merged**
