### PR TITLE
Disable polling

### PR DESCRIPTION
**Pull request by AaronDavidSchneider**
This rather large PR disables polling and therefore increases the stability and quality of the component.

We now subscribe to updates of the alarm and update the state only when necessary. This reduces the amount of computations that need to be performed. It also speeds up the update process.

### CODE REVIEW

**Comment by AaronDavidSchneider** [comment]
I would love to get some feedback on this current PR. It would be nice if you have time to test it @rasmusbe and @christianschneider89.
EDIT: There are some fixes, I first need to do. I will get back to you once they are done.

**Comment by rasmusbe** [comment]
I've only had time to try it briefly but something is broken.
I had one alarm (ID 1) in bedroom when installing.
I added one more alarm, waited a while and it appeared in HA, ID 94.
Then I removed the new alarm (94). 
After a while ID 1 became "Unavailable" in HA and ID 94 still there.
Waited a while more and ID 94 became "Unavailable" too. 
So now I have two unavailable alarms in HA, despite having one active alarm in the Sonos-system.

**Comment by AaronDavidSchneider** [comment]
Thanks for testing @rasmusbe!
I figured that there is still something wrong 😩
Its a bit strange because it has been working on my local development setup but not on my actual setup.
I will revisit it tomorrow and get back once I found a fix.

**Comment by AaronDavidSchneider** [comment]
Now it should work @rasmusbe :D

**Comment by rasmusbe** [comment]
The alarm still becomes unavailable after a while 😞

**Comment by AaronDavidSchneider** [comment]
> The alarm still becomes unavailable after a while 😞

Thanks! I will report back once I find a solution.

**Comment by AaronDavidSchneider** [comment]
This PR will be closed by https://github.com/home-assistant/core/pull/50719.

**Comment by rasmusbe** [comment]
Awesome job getting this PR-ready for core!

**Pull request closed without merging**
